name: flutter_clean_architecture
description: Example project using clean archtecture on flutter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  get_it: ^3.0.1
  shared_preferences: ^0.4.2
  json_annotation: ^3.0.1
  injectable: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  build_runner: ^1.0.0
  injectable_generator: ^0.3.0
  json_serializable: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/json/
